ejercicioFT/Models/Cliente.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ejercicioFT.Models
{
    public class Cliente
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
    }
}

ejercicioFT/Models/OrdenVenta.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ejercicioFT.Models
{
    public class OrdenVenta
    {
        public int Id { get; set; }
        public DateTime FechaEmision { get; set; }
        public int UsuarioId { get; set; }
        public double Total { get; set; }
    }
}

ejercicioFT/Models/OrdenVentaLinea.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ejercicioFT.Models
{
    public class OrdenVentaLinea
    {

        public int Id { get; set; }
        public int OrdenVentaId { get; set; }
        public int ProductoId { get; set; }
        public int Cantidad { get; set; }
        public double Precio { get; set; }


    }
}

ejercicioFT/Models/Producto.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ejercicioFT.Models
{
    
    public class Producto
    {
        [ScaffoldColumn(false)]
        public int Id { get; set; }
        
        [Required(ErrorMessage = "Debe ingresar un nombre")]
        [StringLength(50)]
        public string Nombre { get; set; }
        [Required(ErrorMessage = "Debe ingresar el precio")]
        [Range(0.01, 99.99,
            ErrorMessage = "Ingrese un valor entre 0.01 y 99.99")]
        public Double Precio { get; set; }
        [DisplayName("Tipo de producto")]
        public virtual int TipoId { get; set; }
        [DisplayName("Esta habilitado?")]
        public bool Habilitado { get; set; }
        [DisplayName("Controla stock?")]
        public bool ControlaStock { get; set; }
    }
}

ejercicioFT/Models/Stock.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ejercicioFT.Models
{
    public class Stock
    {
        public int Id { get; set; }
        public int ProductoId { get; set; }
        public int Existencia { get; set; }
    }
}

ejercicioFT/Models/Tipo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ejercicioFT.Models
{
    //Tipos o "clases" de producto
    public class Tipo
    {
        public int Id { get; set; }
        public string Descripcion { get; set; }
    }
}

ejercicioFT/Controllers/NavController.cs
using ejercicioFT.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ejercicioFT.Controllers
{
    public class NavController : Controller
    {
        TiposRepo _tiposRepo = new TiposRepo();

        public PartialViewResult Menu() {
            //"Menu lateral";

            ViewBag.tipos = _tiposRepo.ObtenerTodos();
            return PartialView();

        }
    }
}

ejercicioFT/Controllers/PedidoController.cs
using ejercicioFT.Data;
using ejercicioFT.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ejercicioFT.Controllers
{
    
    public class PedidoController : Controller
    {

        ProductosRepo _productosRepo = new ProductosRepo();
        OrdenVentaRepo _ordenVentaRepo = new OrdenVentaRepo();        
        

        public RedirectToRouteResult AgregarAlPedido(int productoId, int cantidad, int ordenVentaId, string returnUrl)
        {
            Producto producto = _productosRepo.ObtenerPorId(productoId);            
            if (producto != null)
            {
                _ordenVentaRepo.AgregarProductoLinea(_productosRepo.ObtenerPorId(productoId), cantidad, ordenVentaId);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
        public RedirectToRouteResult QuitarDelPedido(int productoId, int cantidad, int ordenVentaId, string returnUrl)
        {
            //Falta logica

            return RedirectToAction("Index", new { returnUrl });
        }

        private OrdenVenta Pedido()
        {
            OrdenVenta ordenVenta = (OrdenVenta)Session["OrdenVenta"];
            if (ordenVenta == null)
            {
                ordenVenta = new OrdenVenta();
                Session["OrdenVenta"] = ordenVenta;
            }
            
            return ordenVenta;
        }
    }
}

ejercicioFT/Controllers/ProductoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ejercicioFT.Models;
using ejercicioFT.Data;

namespace ejercicioFT.Controllers
{
    public class ProductoController : Controller
    {
        ProductosRepo _productosRepo = new ProductosRepo();
        TiposRepo _tiposRepo = new TiposRepo();
        public int ItemsPorPagina { get; set; }
        // GET: Lista
        [Route("Productos/")]
        [Route("")]
        public ActionResult Listado()
        {
            //Paso el objeto para poder utilizar los metodos ya que los necesito
            //para cada articulo que voy listando

            ViewBag.ListaOpciones = _tiposRepo;
            return View(_productosRepo.ObtenerTodos());


        }

        [Route("Productos/Tipo/{categoria}")]
        public ActionResult Listado(int categoria)
        {
            //Paso el objeto para poder utilizar los metodos ya que los necesito
            //para cada articulo que voy listando

            ViewBag.ListaOpciones = _tiposRepo;
            return View(_productosRepo.ObtenerPorTipoId(categoria));


        }

        [Route("Producto/{id}")]
        public ActionResult Detalle(string id)
        {
            Producto prod = _productosRepo.ObtenerPorId(int.Parse(id));            
            ViewBag.tipo = _tiposRepo.ObtenerPorId(prod.TipoId).Descripcion;

            return View(prod);

        }

        [Route("Producto/Nuevo")]        
        public ActionResult Nuevo()
        {

            ViewBag.ListaOpciones = _tiposRepo.ObtenerTodos();

            return View();

        }

        [Route("Producto/Nuevo")]
        [HttpPost]
        public ActionResult Nuevo(Producto producto)
        {
            _productosRepo.Agregar(producto);
            ViewBag.ListaOpciones = _tiposRepo;
            return RedirectToAction("Listado");
        }

        /*public void Index() {
            Response.Write("<h1>Aca se mostrará la lista de productos</h1>");
        }*/
    }
}

ejercicioFT/Views/Nav/Menu.cshtml
    <a class="btn btn-block btn-default btn-lg" href="~/Productos/">Todos</a>

@foreach (var link in ViewBag.tipos)
{
 <a class="btn btn-block btn-default btn-lg" href="~/Productos/Tipo/@link.Id">@link.Descripcion</a>
}

ejercicioFT/Views/Producto/Detalle.cshtml
@model ejercicioFT.Models.Producto

<div class="well">


    <h3>
        <strong>@Model.Nombre</strong>

        <span class="pull-right label label-primary">@Model.Precio.ToString("c")</span>
    </h3>

    <span class="lead">Tipo: @ViewBag.tipo</span>

</div>

ejercicioFT/Views/Producto/Listado.cshtml
@model List<ejercicioFT.Models.Producto>

@{
    ViewBag.Title = "Lista de Productos";
}

@foreach (var item in Model)
{
    //Solo muestra los productos habilitados
    if (item.Habilitado)
    {
        
        @Html.Partial("ProductoContenedor", item)
        
    }
}

ejercicioFT/Views/Producto/Nuevo.cshtml
@model ejercicioFT.Models.Producto

@{
    ViewBag.Title = "Nuevo";
}

<h2>Nuevo PRoducto:</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Producto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Precio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Precio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Precio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipoId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select id="TipoId" class="form-control text-box single-line" name="TipoId">
                    
                    @foreach (var item in ViewBag.ListaOpciones)
                    {

                        <option value="@item.Id">@item.Descripcion</option>

                    }
                </select>

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Habilitado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Habilitado)                    
                    @Html.ValidationMessageFor(model => model.Habilitado, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ControlaStock, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.ControlaStock)
                    @Html.ValidationMessageFor(model => model.ControlaStock, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver", "Listado")
</div>

<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

ejercicioFT/Views/Shared/ProductoContenedor.cshtml
@model ejercicioFT.Models.Producto

    <div class="well">


        <h3>
            <strong>@Model.Nombre</strong>

            <span class="pull-right label label-primary">@Model.Precio.ToString("c")</span>
        </h3>

        @using (Html.BeginForm("AgregarLinea", "Pedido"))
        {
            <div class="pull-right">
                @Html.HiddenFor(x => x.Id)
                @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                <input type="submit" class="btn btn-success" value="Agregar al pedido" />
            </div>
        }

        <span class="lead">Tipo: @ViewBag.ListaOpciones.ObtenerPorId(@Model.TipoId).Descripcion</span>

    </div>

ejercicioFT/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />    
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />

    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <span class="navbar-brand">Fidelity Tools</span>

                <a class="btn btn-default navbar-btn" href="/Producto/Nuevo">Nuevo Producto</a>


            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="row panel">
        <div id="categories" class="col-xs-3">
            @Html.Action("Menu", "Nav")
            
            
        </div>

        <div class="container body-content col-xs-8">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year</p>
            </footer>
        </div>
        </div>

        <script src="~/Scripts/jquery-3.3.1.min.js"></script>
        <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>